### ISSUE TITLE
Where can I get './pkg/editor'?

### ISSUE THREAD

**Issue by blefony** [openmultiplayer/editor#1]
Hi, @Southclaws! Thanks for making this editor. With `npm run dev` I get:

`ERROR in ./index.js`
`Module not found: Error: Can't resolve './pkg/editor' in 'D:\Creating\Apps\threed\editor'`
` @ ./index.js 1:13-35`

What can I do with this? Thank you.

**Comment by Southclaws** [comment]
This project is just an experiment and is not usable at all yet. It will likely be archived as there's a better one being built.
